### ISSUE TITLE
[BUG] No logic in install for certain hard drive sizes

### ISSUE THREAD

**Issue by aarz-snl** [cisagov/LME#104]
In the function data_retention you have this logic: 

  if [ "$DISK_80" -lt 30 ]; then
    echo -e "\e[31m[!]\e[0m LME Requires 128GB of space usable for log retention - exiting"
    exit 1
  elif [ "$DISK_80" -ge 90 ] && [ "$DISK_80" -le 179 ]; then
    RETENTION="30"
  elif [ "$DISK_80" -ge 180 ] && [ "$DISK_80" -le 359 ]; then
    RETENTION="90"
  elif [ "$DISK_80" -ge 360 ] && [ "$DISK_80" -le 539 ]; then
    RETENTION="180"
  elif [ "$DISK_80" -ge 540 ] && [ "$DISK_80" -le 719 ]; then
    RETENTION="270"
  elif [ "$DISK_80" -ge 720 ]; then
    RETENTION="365"
  else
    echo -e "\e[31m[!]\e[0m Unable to determine retention policy - exiting"
    exit 1
  fi
  
  In it's current form there is no logic that accounts for 30-89. So, anyone who tries to install LME falling within that range will be met with "Unable to determine retention policy - exiting"

Additionally, the echo statement that states "LME Requires 128 GB of space" doesn't align with the first rule which states if less than 30 GB.

**Comment by llwaterhouse** [comment]
Fixed with https://github.com/cisagov/LME/pull/143
