### ISSUE TITLE
[BUG] New Generated Passwords Message not displayed

### ISSUE THREAD

**Issue by OSHEAN** [cisagov/LME#128]
## Describe the bug
Followed the instructions in installation guide step 3.2.2 
Fresh install of Ubuntu 22.04 LTS
Ran all commands 
Can see messages displayed that passwords were "Set" Then Setting Roles / passwords
"Creating network lme_esnet
Creating service lme_kibana
Creating service lme_logstash
Creating service lme_elasticsearch
[X] Waiting for Elasticsearch to be ready
...........Elasticsearch is up and running.
[X] Setting elastic user password
{}
[X] Setting kibana system password
{}
[X] Setting logstash system password
{}
[X] Setting logstash writer role
{"role":{"created":true}}
[X] Setting dashboard update role
{"role":{"created":true}}
[X] Creating logstash writer user
{"created":true}
[X] Setting logstash writer password
{}
[X] Creating dashboard update user
{"created":true}
[X] Setting dashboard update user password
{}
[X] Configuring elasticsearch Replica settings
{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [template] in the template "}],"type":"parse_exception","reason":"unknown key [template] in the template "},"status":400}{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [[_all]]","index_uuid":"_na_","index":"[_all]"}],"type":"index_not_found_exception","reason":"no such index [[_all]]","index_uuid":"_na_","index":"[_all]"},"status":404}
[X] Generating files_for_windows zip
  adding: tmp/lme/ (stored 0%)
  adding: tmp/lme/root-ca.crt (deflated 25%)
  adding: tmp/lme/wlbclient.crt (deflated 24%)
  adding: tmp/lme/wlbclient.key (deflated 24%)
  adding: tmp/lme/winlogbeat.yml (deflated 52%)
test of /opt/lme/files_for_windows.zip OK
[X] Setting Elastic pipelines
{"acknowledged":true}[X] We think your main disk is 98G
[!] Unable to determine retention policy - exiting
username@server:/opt/lme/Chapter 3 Files$"

## To Reproduce
I reverted my VM back to pre-ELK install snapshot.
Re-ran the install commands to see if I missed a message. Same results as first time.
I read the FAQs and discussions and reviewed the troubleshooting guide but didn't see any similar issues reported.

**Server:**
- OS: Ubuntu 22.04
- Software Versions: latest version LME v1.2.0
  - ELK: [e.g. 8.7.1]
  - Docker: [e.g. 20.10.23, build 7155243]
- The output of these commands: 
```
free -h
total        used        free      shared  buff/cache   available
Mem:            15Gi        13Gi       151Mi       1.0Mi       2.1Gi       1.7Gi
Swap:          4.0Gi        19Mi       4.0Gi

df -h 
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              1.6G  1.5M  1.6G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   98G   11G   82G  12% /
tmpfs                              7.9G     0  7.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  129M  1.7G   8% /boot
tmpfs                              1.6G  4.0K  1.6G   1% /run/user/1000

uname -a 
Linux lme-db 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

I expected to see a message with all usernames/passwords as described in the guide at step 3.2.2

**Comment by aarz-snl** [comment]
Do you have the capability to increase your disk size? /dev/mapper/ubuntu--vg-ubuntu--lv having over 100G should resolve your issue.

**Comment by OSHEAN** [comment]
I've been looking this over all afternoon, even reading through the script!  When I deployed my VM, it was configured with a 500GB hard drive. So it didn't occur to me that, that was the issue.  I just finished extending the LVM of 100GB to 100% of the disk.  And successfully deployed ELK.  Thank you and so sorry for this oversight!

**Comment by aarz-snl** [comment]
No problem. No oversight on your side. It's actually a bug that will be fixed in next release: 

https://github.com/cisagov/LME/issues/104

The script does 80% of the hard drive size which would put 98GB into 'bug territory'
