### ISSUE TITLE
[BUG] Healthcheck Dashboard has multiple issues.

### ISSUE THREAD

**Issue by rishagg01** [cisagov/LME#129]
## Describe the bug
The Healthcheck dashboard panels are using field name user.name for filtering data. They should use winlog.user.name.
Also the Dashboard header is not showing correctly.
The visualization for Active Admin users is not working correctly either.

## Expected behavior
The panels should at minimum always display the Admin User for the computers.
The Dashboard header should display link to all other dashboards.

**Comment by llwaterhouse** [comment]
This issue has been resolved with release 1.3.0
