### ISSUE TITLE
Dashboard options and Alerting

### ISSUE THREAD

**Issue by ddiabe** [cisagov/LME#13]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by llwaterhouse** [comment]
Added Alerting and health overview dashboards in release 1.3.0
