### ISSUE TITLE
Research into if Kibana can send alerts/notifications to a user

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/LME#131]
**Is your feature request related to a problem? Please describe.**

The alert dashboard provides threat hunting insight for users, but is there a way for notifications to be sent by email or other method if an alert occurs? 

**Describe the solution you'd like**

Link to Elastic documentation or provide steps to setup within user environment 

**Describe alternatives you've considered**

**Additional context**

**Comment by Gschragg** [comment]
Has anyone figured out how to setup alerting for elastic/kibana without paying for elastics packages.

**Comment by mitchelbaker-cisa** [comment]
https://github.com/jertel/elastalert2 is an option, which would provide us alerting/notification functionality without relying on elastic's packages

**Comment by safiuddinr** [comment]
No longer needed as we will be researching elastalert.  Kibana will not be used due to licensing cost.
