### ISSUE TITLE
[BUG] ERROR 2150859046 & ERROR 5 in step 1.1-2.2.3

### ISSUE THREAD

**Issue by Gschragg** [cisagov/LME#146]
## Describe the bug
I've already made it to chapter 2 of the setup process and was about to move onto Chapter 3, before I was able to get to chapter 2 however I ran into a problem with the collector and the client where it wasn't recognizing the client I have been using for testing. I was given the following error code in event viewer>Eventlog-ForwardingPlugin.

![image](https://github.com/cisagov/LME/assets/156207169/627e2559-bc15-4fed-93e1-6e42dcd6c03c)

The WEC also wasn't receiving a connection from the client, after a days worth of troubleshooting found out COM+ needs to be allowed on the WEC for it to receive that connection. I'm still given that error but at least the client is recognized on the WEC.

So I went onto Chapter 2 hoping maybe the problem will work itself out, now that I've completed chapter 2 I'm having a problem where the client isn't sending over any logs, the task scheduled to run update.bat does work and sysmon64.exe is running as a service on the cilent, but when I visit sysmon on event viewer I am prompted with

![image](https://github.com/cisagov/LME/assets/156207169/b0ef631a-6907-4def-92f8-89081d45c8ed)

which seems like a very generic error, at this point I'm holding off from going to chapter 3 until I can resolve 1 if not both problems.

I have double checked all steps and made sure all GPOs are configured correctly, any help would be much appreciated, I'm thinking I might have to nuke the WEC server and start fresh but I'll hold off for a couple days till I can get an answer from anyone.

Couldnt tell you about reproducing it because it started all the way in step 1 of chapter 1

Thank you in advanced!

## To Reproduce
After setting up chapter 1 and 2, procced to event viewer on the client and the WEC and looking at sysmon we can see an Access Denied (5) error, and on the same machine looking at the Eventlog-ForwardingPlugin we are also given a lot of errors as show in the snapshot above. Going to the WEC and going to the Eventlog-fFprwardingPlugin folder on event viewer we arnt given any up to date logs on anything being preformed on the client.

### Please complete the following information
**Desktop:**
 - OS: Windows 11
 - Browser: Google Chrome Version 120.0.6099.200
 - Software version: Sysmon v15.12
**Server:**
- OS: Windows Server 2019
- Software Versions:
 N/A
- Relevant container logs: 
N/A

## Expected behavior
Should see data in the sysmon eventlog, should also see sysmon logs show up in the event collector.

## Screenshots
![image](https://github.com/cisagov/LME/assets/156207169/14267856-6f96-4145-bf42-7641f94ff15b)
![image](https://github.com/cisagov/LME/assets/156207169/627e2559-bc15-4fed-93e1-6e42dcd6c03c)
![image](https://github.com/cisagov/LME/assets/156207169/b0ef631a-6907-4def-92f8-89081d45c8ed)

**Comment by aarz-snl** [comment]
Did you perform the prereqs as well: https://github.com/cisagov/LME/blob/main/docs/markdown/prerequisites.md

What were the results of Chapter 1 checks? 

https://github.com/cisagov/LME/blob/main/docs/markdown/chapter1/chapter1.md#chapter-1---checklist

You should have a successful connection in Subscriptions and logs going to your windows event log - fowarded events before moving on to chapter 2. All chapter 2 does is install sysmon.

**Comment by Gschragg** [comment]
For chapter 1, I was seeing the client on the subscriptions tab, however when looking at eventlog-forwardingplugin I am receiving an error pretty constantly that states the following.  
The forwarder is having a problem communicating with subscription manager at address http://[redacted]/wsman/SubscriptionManager/WEC.  Error code is 2150859046 and Error Message is <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859046" Machine="LT22-GSCHRAGG.private.sparcc.org"><f:Message>WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. </f:Message></f:WSManFault>.

**Comment by Gschragg** [comment]
> For chapter 1, I was seeing the client on the subscriptions tab, however when looking at eventlog-forwardingplugin I am receiving an error pretty constantly that states the following. The forwarder is having a problem communicating with subscription manager at address http://[redacted]/wsman/SubscriptionManager/WEC. Error code is 2150859046 and Error Message is <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859046" Machine="LT22-GSCHRAGG.private.sparcc.org"><f:Message>WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. </f:Message></f:WSManFault>.

Also yes i did check prerequisites

**Comment by aarz-snl** [comment]
I would start by double checking your GPOs making sure any fqdn configurations are correct. if all your GPO settings are correct have they been implemented on the client and server locally successfully?



verify there's no other security functions on your network that could be preventing communication... vpns, etc. 

check dns name resolution between the client and server

try pinging wec.server.com (whatever it is ) from the client, and do the same from the server to client. Do nslookup as well for good measure.

**Comment by Gschragg** [comment]
Okay, found that the problem was that the name for the FQDN was not set to the exact same name, so it is forwarding the logs from sysmon, the only other problem which im not sure if this so much of a problem or intended. I have a warning Event that says "The subscription lme is created, but one or more channels in the query could not be read at this time." and the event before that is an information event that only pops up on a gpupdate or restart and its reads as follows "The subscription lme is unsubscribed." but I did look at the collector and as I type this it is still is having events forwarded to it.

**Comment by aarz-snl** [comment]
For future improvements / documentation -- could you share an example of what you had vs what you eventually changed it to after troubleshooting correlated with the specific step in the instructions? Is there a step that could have been included that would have prevented your mistake?

**Comment by aarz-snl** [comment]
also any information on your com+ troubleshooting would be good. com+ and winrm shouldn't be related so I'm confused on that one

**Comment by Gschragg** [comment]
![image](https://github.com/cisagov/LME/assets/156207169/9238d6e7-4b44-4028-bf8b-8c0b15b45a6d)
When looking at the eventforwarding GPO I only had the machine name in the field I didn't have our Domain naming scheme following, which was an oversight by me. Now for the COM+ I'm not entirely sure how this fixed it, but when I first initialized the WEC as a subscription it prompted me with the normal yes or no prompted but after selecting yes an error was thrown at me and it said something about connection errors with this server, didn't get a good glimpse at it but I remember seeing a section of the error that was giving suggestions for fixing this error, and it gave the obvious fix of checking to see if you can ping the server from another remote client, and to check my WMI and COM+ Remote Administration settings. My team and I didn't really decide to look into that because I had forgot about that error. That error is also a 1 time pop-up so unfortunately I'm unable to supply a screenshot of it.

**Comment by llwaterhouse** [comment]
Thank you for your comments.
