### ISSUE TITLE
[BUG] deploy.sh data_retention failure

### ISSUE THREAD

**Issue by arunseelagan-cisa** [cisagov/LME#177]
## Description
While running the LME Chapter 3 File/deploy.sh install command on an server with 2TB of storage, the data_retention function fails because the DF_OUTPUT (line 538) returns a number in TB not in GB (which is the assumption the code currently makes). 

The regex passed to grep when setting DISK_DEV (line 541) assumes the DF_OUTPUT value contains a GB value. 

This faulty assumption results in erroneous values for DISK_DEV and DISK_SIZE.

The entire install process fails as a result.  

## To Reproduce
Install LME on a server with 1+TB of storage

## Expected behavior
Fix the deploy script to force output in GB, so the regex won't fail.

df -h -BG -l -t ext4 ...

**Comment by aarz-snl** [comment]
Thanks for pointing this out we have a branch with necessary changes in place: 

https://github.com/cisagov/LME/blob/awarz-177-bug-deploysh-data_retention-failure/Chapter%203%20Files/deploy.sh

DF_OUTPUT="$(df -BG -l -t ext4 --output=source,size /var/lib/docker)"

**Comment by aarz-snl** [comment]
This has a PR open for review... if install in a timely manner is necessary you can use the current code from the branch for testing by changing deploy.sh to match
