### ISSUE TITLE
Write flags to InstallTestBed in *.output.log

### ISSUE THREAD

**Issue by llwaterhouse** [cisagov/LME#193]

**Comment by cbaxley** [comment]
Do you want this inside of the linux container or in the log that is created with the passwords on the cloudshell where you ran the installers?

**Comment by llwaterhouse** [comment]
In the log

**Comment by cbaxley** [comment]
So the log that is in Chapter 3?
Thanks,
Clint Baxley
***@***.***

Windows is great... I used it to download Linux.

**Comment by llwaterhouse** [comment]
I think it would be most useful to add InstallTestBed's flags to testing/<ResourceGroup>.password.txt so that when someone was starting a cluster they knew what was installed on it.
