### ISSUE TITLE
./deploy.sh keeps hanging on waiting for elasticsearch to be ready then exit after 25 attempts

### ISSUE THREAD

**Issue by imran196** [cisagov/LME#196]
Hello, 

tried deploying with the .sh and i keep getting ./deploy.sh keeps hanging on waiting for elasticsearch to be ready then exit after 25 attempts, 

I tried to look through other issue threads and tried the fixes but it does not work. 

specs of server ubuntu 22.04 64 bit, 700gb HD tried with 16gb/20gb and 32gb ram same issue
did a complete server rebuild still have the same issue 

any help is appreciated

Thanks

**Comment by llwaterhouse** [comment]
Hello,
This issue is documented in FAQ.md and Troubleshooting.md inside LME's Docs. If it still doesn't work after you've tried the debugging steps listed, please submit a full bug report (from the template) and list the results you've had, so we can understand more about your issue and system.  Thank you.

**Comment by imran196** [comment]
Hello tried the troubleshooting but no joy as this is a fresh install the command for the troubleshooting is foe existing installations

see below for bug report 

## Describe the bug
/deploy.sh keeps hanging on waiting for elasticsearch to be ready then exit after 25 attempts

## To Reproduce
installed ubuntu 22.04 64 bit gui 
did apt-get update 
transferred files for Chapter 3 files to /opt/lme
ran ./install.sh as sudo 
ran through installations and then keeps hanging on waiting for elasticsearch to be ready then exit after 25 attempts


### Please complete the following information
**VM server*
 - Ubuntu 22.04 



## Expected behavior
installation finished and showing dashboard password

Thanks

**Comment by llwaterhouse** [comment]
try running
```
 ./deploy uninstall
sudo docker volume rm lme_esdata
sudo docker volume rm lme_logstashdata 
./deploy install
```

**Comment by imran196** [comment]
Thanks both il give it a try and report back!

**Comment by imran196** [comment]
hello i tried the solution in #172 but the command elasticsearch-reset-password command not found, it says i need to install a new version of lme, i thought the one in this thread is hte newest 

any help with this? 

Thanks

**Comment by imran196** [comment]
hello, 
so after scratching my head, I did a fresh install wiht ubuntu 23 which is the latest and that installed ok

**Comment by llwaterhouse** [comment]
Thank you for letting us know.
