### ISSUE TITLE
Evaluate other logging solutions (e.g. Wazuh) same as ticket #127

### ISSUE THREAD

**Issue by llwaterhouse** [cisagov/LME#20]
What alternate logging solutions do we want to evaluate?  Wazuh?  Greylog?  Zeek?

See ticket#127 https://github.com/orgs/cisagov/projects/63?pane=issue&itemId=60616342

**Comment by agardnerIT** [comment]
If the collector was able to output logs in OpenTelemetry compatible format, these logs could be sent from LME to an OpenTelemetry collector and thus (with zero additional effort) any backend which supports OpenTelemetry log ingest can accept LME output.

**Comment by dcernoch** [comment]
Move to LME 2.0 Epic/Milestone

**Comment by dcernoch** [comment]
Make part of LME 2.0

**Comment by safiuddinr** [comment]
We have evaluated multiple products and decided to go with Wazuh as MVP Reach item. Research is complete.

**Comment by jdu2600** [comment]
Was Elastic Endpoint one of the products evaluated?

* https://www.elastic.co/docs/current/integrations/endpoint
* https://github.com/elastic/protections-artifacts
* https://www.elastic.co/security-labs/the-elastic-container-project
