### ISSUE TITLE
Dashboard spamming login events from the Event Log Collector server itself

### ISSUE THREAD

**Issue by SoyG** [cisagov/LME#22]
# 🐛 Summary #

In the Activity Dashboard I'm seeing thousands of logons from the Windows Server that I configured as the Event Log Collector. The WEC sent 33K, while the other 6-7  clients only sent about a dozen logs so far each.

## Expected behavior ##

I can't tell if it's showing the clients logs, or if these are all generated by the server itself. Is this normal behavior for the collector and I should create an exclusion?

## Any helpful log output or screenshots ##

In the screenshot the Event Collector server name is "WEC". The other 6-7 clients are sending logs but so far only a dozen logs each.

![Screenshot 2023-11-07 162021](https://github.com/cisagov/LME/assets/14953783/786458a5-5aeb-4efa-9225-ff0039d67970)

**Comment by codykal** [comment]
I'm actually having the exact same issue, the event collector itself is showing thousands of login attempts, whereas only 2 of my other 32 clients are showing any login attempts whatsoever.

**Comment by mreeve-snl** [comment]
We'll be adding documentation around issues like this to help with filtering out unnessary content by adding filters to the dashboard

For now, you can use a `regexp` filter at the top of the dashboard to get rid of these "fluff" events. 
I'm not a windows administrator, so if other users know exactly what sort of backend service communication is creating these logs I'm all ears. 

Anyway, to filter them out of the dashboard you can do this: 
1. Click the `Add filter`: 
2. Click `Edis as DSL` to add a regexp filter:  
```
{
  "bool": {
    "filter": [
      {
        "match_phrase": {
          "event.code": "4624"
        }
      }
    ],
    "must_not": [
      {
        "regexp": {
          "winlog.event_data.TargetUserName": ".*$.*"
        }
      }
    ]
  }
}
```

The above filters out for the [4624](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4624) events any TargetUserName that has a `$` in the field. 

For my test environment this makes my `User Security` Dashboard go from 5K events to 120 events: 


![Before](https://github.com/cisagov/LME/assets/147089975/cec40598-743b-4d96-bf86-28770e97567c)

![After](https://github.com/cisagov/LME/assets/147089975/6d6a189e-4fc4-43c6-a4b0-24378e6252b6)

**Comment by llwaterhouse** [comment]
We have added a filter in release v 1.1.0.  If you still have an issue, please let us know.

**Comment by SoyG** [comment]
> We have added a filter in release v 1.1.0. If you still have an issue, please let us know.
Thank you. But I'm not seeing how to upgrade to 1.1.0 ?

**Comment by llwaterhouse** [comment]
Release 1.1.0 will be published next week.  In the meantime, you can use the steps to filter out events in the response above.
