### ISSUE TITLE
Add rebasing current release branch when there are patch fixes to release notes.

### ISSUE THREAD

**Issue by llwaterhouse** [cisagov/LME#221]

**Comment by llwaterhouse** [comment]
When we make patch fixes(e.g.1.3.3), we need to rebase the current release branch (e.g. 1.4.0) so that it has the latest bug fixes.  Add this step to the release notes.

**Comment by mitchelbaker-cisa** [comment]
Resolved https://github.com/cisagov/LME-PRIV/pull/126
