### ISSUE TITLE
Sysmon install problem through GPO on clients

### ISSUE THREAD

**Issue by wesliix** [cisagov/LME#224]
Hello, i'm having a problem with installing Sysmon through GPO on my clients.

I am installing Sysmon through GPO on the Domain Controller, i put in all the files in  \\domain.xxx\sysvol\domain.xxx\LME\Sysmon

i put the following files in there:
sysmon.xml
sysmon64.exe
update.bat 

And i put the sigcheck64.exe file in  \\domain.xxx\sysvol\domain.xxx\LME

Now, i made a Policy in Group Policy Management called LME-Sysmon-Task

With those directions, i made a Scheduled Task to install Sysmon on my clients.

It is running the task but it is not installing the Sysmon service on my clients.

Can someone help me out please?

Thanks in advance

wesliix

**Comment by llwaterhouse** [comment]
Hello, thank you for contacting us.  Have you gone through the FAQ and troubleshooting docs?  Please resubmit this ticket using the BUG Issue template after you have followed the steps described in the template.

Thank you.

**Comment by wesliix** [comment]
Hey,

I have recently found the issue, it was a error with selecting the network path in Scheduled Tasks. I made a little typo.

Thank you for the reply @llwaterhouse , next time i will submit the ticket in the right place.

wesliix

**Comment by llwaterhouse** [comment]
Thanks for letting us know how you fixed your issue wesliix.

This is the correct place to submit, we just ask that bugs be submitted in the template so we have the necessary information to respond.  Did the option of using the Bug template come up when you created the issue?
