### ISSUE TITLE
Failed to initialize docker swarm 

### ISSUE THREAD

**Issue by james-wallace114** [cisagov/LME#236]
## Describe the bug
When instaling via Ubuntu 22.04 LTS Desktop -> I run the deply script and then after the docker install I get an error that says:
Failed to initialize Docker Swarm (is 10.0.2.15 the correct IP address?) - exiting

## To Reproduce
Setup is on Latest Version of VirtualBox -> Ubuntu 22.04 LTS Desktop, 12gb Ram and plent HDD space with 2 x CPU

**Comment by cbaxley** [comment]
If you do a
docker ps
what do you see?

Thanks,
Clint Baxley

**Comment by llwaterhouse** [comment]
James, in order to be able to best respond to your issue, please resubmit this issue with the BUG template after going through all of the troubleshooting steps.

Thank you.

**Comment by safiuddinr** [comment]
User needs to resubmit the bug using the right template. We have not heard any feedback for over a month. Closing the ticket for now.
