### ISSUE TITLE
Elastic interface logging in page {"statusCode":404,"error":"Not Found","message":"Not Found"}

### ISSUE THREAD

**Issue by markofsuccess** [cisagov/LME#241]
# 🐛 Summary #

This issue is regarding chapter 3 logging in to the web interface https://<LINUX_SERVER_IP/HOSTNAME>

Everything is setup and running. The docker containers on the linux server is running and Winlog is running on the Windows Event Collector. 

For the Windows Event Collector:

The inbound firewall rule: TCP port 5985 is open to accept connections from the clients.
The outbound rule is open : TCP port 5044 is open for outbound connections to the Linux server 

For the Linux Server:

Inbound: The TCP port 5044 is open for inbound connections from the Windows Event Collector.

What could be causing this? Any help is much appreciated, thank you.
## To reproduce ##

I log in with my elastic credentials in the web browser interface and then I get this message:
{"statusCode":404,"error":"Not Found","message":"Not Found"}

## Expected behavior ##

What did you expect to happen that didn't?

To get forwarded to the LME GUI after logging in.

## Any helpful log output or screenshots ##

Paste the results here:
<img width="476" alt="image" src="https://github.com/cisagov/development-guide/assets/48018544/c7edec84-b65c-487a-861d-e6e483f941fc">

```console

```

Add any screenshots of the problem here.

**Comment by jsf9k** [comment]
@markofsuccess - Here is [a link to the issue in its new home](https://github.com/cisagov/LME/issues/241).

**Comment by jsf9k** [comment]
No problem at all.

**Comment by llwaterhouse** [comment]
Hello @markofsuccess,

Thank you for reaching out. It seems the problem might stem from slight variations in following the installation guidelines.
Could you please review the troubleshooting guide [here](https://github.com/cisagov/LME/blob/main/docs/markdown/reference/troubleshooting.md)?

Please make sure that the services are running in the docker containers.

If you still encounter issues deploying LME, submit a bug report [here](https://github.com/cisagov/LME/issues), ensuring you provide all details requested in the Bug template. This way we will have the information we need to best support you.

Thanks!

**Comment by safiuddinr** [comment]
See Linda's comment above.
