### ISSUE TITLE
Secure by Design goal for LME 2.0 Architecture

### ISSUE THREAD

**Issue by dcernoch** [cisagov/LME#253]

**Comment by aarz-snl** [comment]
I do like podman as an option here as I think we can use the exact same docker compose either way and would provide rootless containers. 

I also like that it appears we could use podman secrets without the use of docker swarm: 

https://docs.podman.io/en/latest/markdown/podman-secret.1.html

Docker secrets requires swarm -- this would allow us to use secrets and rid ourselves of the complexity of docker swarm. Swarm is really in situations where you need scaling, load balancing etc -- and that just doesn't align with the missions of a simple one server deployment

**Comment by llwaterhouse** [comment]
Andrew you bring up an important point.  Who are LME's potential clients?

How many clients can one server support?  What factors besides disk size have to be taken under consideration?
If one server can support as many clients as we think is reasonable, then we can use that as a guideline as we move forward.

"Small"  means different things to different people.  We need to have a clearer definition of who we are building LME for.

**Comment by ddiabe** [comment]
Will move ticket to back log. Haven't really put alot of time on it.

**Comment by ddiabe** [comment]
We spoke about this in our TEM meeting last week. We added this as One of the features LME 2.0 will have (secure by dfault, enforce principles of least privilege across entire LME).

https://usdhs.sharepoint.com/:x:/r/teams/LoggingMadeEasy784/_layouts/15/doc2.aspx?sourcedoc=%7B3E3CA14A-0E21-45CF-80E0-C72982F60C0C%7D&file=LME%202.0%20Features.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1
