### ISSUE TITLE
User Experience (easy install, deployment time )

### ISSUE THREAD

**Issue by dcernoch** [cisagov/LME#254]

**Comment by safiuddinr** [comment]
This ticket is covered by Clints tickets.

**Comment by ddiabe** [comment]
https://usdhs.sharepoint.com/:x:/r/teams/LoggingMadeEasy784/_layouts/15/doc2.aspx?sourcedoc=%7B3E3CA14A-0E21-45CF-80E0-C72982F60C0C%7D&file=LME%202.0%20Features.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1

**Comment by cbaxley** [comment]
This is installing easily using ansible at this time. We are still working out bugs in using proxies. I have done 5 installs without a failure.
