### ISSUE TITLE
Q/A: unit tests and threat emulation

### ISSUE THREAD

**Issue by dcernoch** [cisagov/LME#255]

**Comment by ddiabe** [comment]
https://usdhs.sharepoint.com/:x:/r/teams/LoggingMadeEasy784/_layouts/15/doc2.aspx?sourcedoc=%7B3E3CA14A-0E21-45CF-80E0-C72982F60C0C%7D&file=LME%202.0%20Features.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1

**Comment by safiuddinr** [comment]
Closing per comment above.
