### ISSUE TITLE
Add a few features to ansible script

### ISSUE THREAD

**Issue by mreeve-snl** [cisagov/LME#387]
We need to offer alternative to sysctl rule, so easiest way to do this is have a firewall rule forward 443 (and other ports) to 8443 or however we want to redirect ports

~~n addition, we need to allow for adding custom passwords~~

**Comment by mreeve-snl** [comment]
the above actually will get implemented later, and the custom passwords is setup now :)

**Comment by safiuddinr** [comment]
Completed.
