### ISSUE TITLE
Research ElastAlert 2 integration or another tool for free alerting

### ISSUE THREAD

**Issue by safiuddinr** [cisagov/LME#412]

**Comment by mreeve-snl** [comment]
Ideally we have the following out of this: 

1. podman command to start elastalert: 
```bash
podman run --net=es_default -d --name elastalert --restart=always -v $(pwd)/elastalert.yaml:/opt/elastalert/config.yaml -v $(pwd)/rules:/opt/elastalert/rules docker.io/jertel/elastalert2 --verbose
```
2. rules for alerting on detections: (./config/elastalert/rules/)
  1. monitor elasticsearch detections
  2. monitor wazuh detections
2. elastalert config: (./config/elastalert/elastalert.yml)
  4. email out detections trigger 
3. documentation around elastalert for the above
