### ISSUE TITLE
add documentation and ensure steps are tested on 2.0 for data management

### ISSUE THREAD

**Issue by mreeve-snl** [cisagov/LME#464]

**Comment by mreeve-snl** [comment]
some simple cli things that we can run to manage data state of logs, answer FAQ we've seen people have, and have a method for backups... I think /opt/lme/backups mounted in the container is good enough

we have some of this already in the old docs, just has to get modified for our new architecture and add a bit of documentaiton so users can understand hardware requirements for data storage and operation

**Comment by safiuddinr** [comment]
Mikey and Andrew added documentation related to backups, index and volume.
