### ISSUE TITLE
Modify the dashboard menu to remove the home page and link new dashboards for 1.1.0

### ISSUE THREAD

**Issue by cbaxley** [cisagov/LME#47]
# 💡 Summary #

What is the work, as a high-level summary?
Modify the dashboard menu to remove the home page and link new dashboards for 1.1.0

Why does this work belong in this project?

This would be useful because we are removing the home page. 

## Acceptance criteria ##

All of the dashboards have the dashboard menu that links to all of the other dashboards. 

- [ ] Criterion

**Comment by llwaterhouse** [comment]
Work has been done, doing final testing.
