### ISSUE TITLE
Introduction of automation tools 

### ISSUE THREAD

**Issue by ddiabe** [cisagov/LME#6]
# 🐛 Summary #
Using automation tools like Ansible, puppet for configuration management to facilitate the installation of LME.
What's wrong? Please be specific.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by llwaterhouse** [comment]
This issue is not needed anymore
