### ISSUE TITLE
Unable to bring up webpage

### ISSUE THREAD

**Issue by jp18018** [cisagov/LME#77]
Recently installed LME and was working fine.  Can't access the Elastic Search webpage.  (site cannot be reached).
I'm able to SSH to the server and can run: sudo docker stack ps lme.
I get a few running and a few shutdowns.

Other than starting all over again, how can I troubleshoot?

**Comment by cbaxley** [comment]
Can you give me the output of `docker ps`?
Can you give the output of `sudo ls -l /opt/lme`?

**Comment by jp18018** [comment]
docker ps:
704dbb699a56   docker.elastic.co/elasticsearch/elasticsearch:8.7.1   "/bin/tini -- /usr/l…"   11 seconds ago   Up 5 seconds (health: starting)    9200/tcp, 9300/tcp   lme_elasticsearch.1.kg4npo8c7p6jxftbnnvmh6lz9
3271e63a9861   docker.elastic.co/kibana/kibana:8.7.1                 "/bin/tini -- /bin/b…"   12 minutes ago   Up 11 minutes (health: starting)   5601/tcp             lme_kibana.1.imzr38kuslyqbqflljexnmi6c
1f682202a6b2   docker.elastic.co/logstash/logstash:8.7.1             "/usr/local/bin/dock…"   4 days ago       Up 4 days (healthy)                5044/tcp, 9600/tcp   lme_logstash.1.eve8ifuc96vc6s32rto0tmkg1

ls -la /opt/lme:
 sudo ls -l /opt/lme
total 80
drwx------ 2 root root  4096 Nov  8 17:54  backups
drwx------ 2 root root  4096 Nov  8 17:54  build
drwx------ 3 root root  4096 Nov  8 17:54 'Chapter 1 Files'
drwx------ 4 root root  4096 Nov  8 17:54 'Chapter 2 Files'
drwx------ 3 root root  4096 Nov  8 17:55 'Chapter 3 Files'
drwx------ 3 root root  4096 Nov  8 17:54 'Chapter 4 Files'
-rwx------ 1 root root   933 Nov  8 17:57  dashboard_update.sh
drwx------ 4 root root  4096 Nov  8 17:54  docs
-rw------- 1 root root  6717 Nov  8 17:57  files_for_windows.zip
-rw------- 1 root root 18886 Nov  8 17:54  LICENSE
-rw------- 1 root root    40 Nov  8 17:57  lme.conf
-rwx------ 1 root root    56 Nov  8 17:57  lme_update.sh
-rw------- 1 root root  4270 Nov  8 17:54  README.md
drwx------ 2 root root  4096 Nov  8 17:54  testing

**Comment by cbaxley** [comment]
Ok. Try this 
`sudo chown -R 1000:1000 /opt/lme/backups` and see if the `docker.elastic.co/elasticsearch/elasticsearch:8.7.1` container stays running. That may fix it.

**Comment by jp18018** [comment]
That seems to have helped.
