### ISSUE TITLE
Research automation for tagging and release notes

### ISSUE THREAD

**Issue by mitchelbaker-cisa** [cisagov/LME#82]
**Is your feature request related to a problem? Please describe.**

During the release of v1.1.0 of LME we discussed automation of the tagging process and deploying releases automatically. Currently this process is done manually. The purpose of this issue is to research into ways we can go about this, then execute on a method that works best for the team. 

**Describe the solution you'd like**

- Automate tagging based on the branch name
    - when the release-1.1.0 branch is merged into main, the new release shall be marked v1.1.0
- Automate creation of release notes 
    - Header should contain the following information: [\<version-number>] - Timberrrrr! - \<date-of-release> 
    - Sections for what was added, changed, fixed, and additional notes. 
 
Considerations to look into: 
1. Can we provide specific details to be included in the release markdown (under added, changed, fixed, etc.) or are we restricted to what the commit messages were?
2. How can we better utilize Github Actions to test LME prior to a release? 

**Describe alternatives you've considered**

There's most likely some sort of Git release manager tool that already exists: https://github.com/GitTools/GitReleaseManager

**Additional context**

What our release notes currently look like: 
![Screenshot 2023-11-30 142217](https://github.com/cisagov/LME/assets/149098823/f2deb32c-00c5-4b91-a3b0-2797b57c1fea)

Sample from GitReleaseManager: https://github.com/chocolatey/ChocolateyGUI/releases/tag/0.12.0

This issue is complete when: 
- [ ] https://github.com/cisagov/LME/issues/135 is resolved

**Comment by mitchelbaker-cisa** [comment]
https://github.com/semantic-release/semantic-release seems promising, can be automated with CI

**Comment by llwaterhouse** [comment]
This looks really promising!  Yesterday Roger said that he wants user-friendly release notes, not just commit messages.

**Comment by mitchelbaker-cisa** [comment]
With semantic-release we could automatically determine the next semantic version number, but it requires commit messages to be prefixed with fix():/feat():/ which would be another workflow to introduce to the team. (There are commit linters for this which would make it easy to enforce)

I suggest we create a draft release in Github, the release version number and branch to target can be specified here ahead of time. Release notes can also be generated directly from a draft release. One thing to note is that the name given to a PR will be the commit message displayed, so good PR names are important if we want to automate this process. 

Example of generated release notes: 

![Image](https://github.com/cisagov/LME/assets/149098823/b652fa20-0374-4151-b1b2-fc7d30836f67)

**Comment by mitchelbaker-cisa** [comment]
https://github.com/softprops/action-gh-release GitHub action for automating creation of release

**Comment by mitchelbaker-cisa** [comment]
https://github.com/nektos/act is a tool for testing github actions locally. Currently testing the new github action I created on a forked repo of LME, as to not pollute the main branch.

**Comment by mitchelbaker-cisa** [comment]
Can successfully create a draft release from Github Actions. Has prepopulated tags, title, custom body and generated release notes. 

Need to test what PRs or other information is included under "What's Changed" 
Can remove the release.yml file and labels as these won't be needed. Will need to look into a way to pull all PRs into a given branch, such as release-1.3.4 and then display these in release notes as opposed to pulling them manually. 

With this new GitHub Action anyone from the dev team can run the workflow, simply specify the release name and release version, do a final check that the draft is all set, and release. This will greatly simplify our current release process. 

![Image](https://github.com/cisagov/LME/assets/149098823/079a9a47-a5a8-480d-a136-f773ca4d867b)
