### ISSUE TITLE
[BUG] Error code is 12175

### ISSUE THREAD

**Issue by murphypa271327** [cisagov/LME#88]
## **BEFORE CREATING THE ISSUE, CHECK THE FOLLOWING GUIDES**: 
 - [ ] [FAQ](https://github.com/cisagov/LME/blob/main/docs/markdown/reference/faq.md)
 - [ ] [Troubleshooting](https://github.com/cisagov/LME/blob/main/docs/markdown/reference/troubleshooting.md)
 - [ ] Search current/closed issues for similar questions, and utilize github/google search to see if an answer exists for the error I'm encountering.  

If the above did not answer your question, proceed with creating an issue below: 

## Describe the bug
The forwarder is having a problem communicating with subscription manager at address https://example.com:5985/wsman/SubscriptionManager/WEC. Error code is 12175 and Error Message is <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="12175" Machine="client.com><f:Message>The server certificate on the destination computer (example.com:5985) has the following errors:
Encountered an internal error in the SSL library. </f:Message></f:WSManFault>.

## To Reproduce
Collector is a Windows server 2019, test systems are Window Server 2022. Went through the procedures multiple times, resulting in same error. Tried the listed troubleshooting snippets and a few of my own to ensure that the servers were communicating on the correct ports.

To increase the speed and relevance of the reply we suggest you list down debugging steps you have tried, as well as the following information:

### Please complete the following information
**Collection Server**
 - OS: Server 2019
 - Browser: Edge / TLS 1.2
 - Software version: Sysmon v15.11.0.0, Winlogbeat 8.5.0]

**Server:**
- OS: [e.g. Ubuntu 22.04]
- Software Versions:
  - ELK: [e.g. 8.7.1]
  - Docker: 
 docker-buildx-plugin/jammy,now 0.11.2-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce-cli/jammy,now 5:24.0.7-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce-rootless-extras/jammy,now 5:24.0.7-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce/jammy,now 5:24.0.7-1~ubuntu.22.04~jammy amd64 [installed]
docker-compose-plugin/jammy,now 2.21.0-1~ubuntu.22.04~jammy amd64 [installed]

- The output of these commands: 
```
free -h
               total        used        free      shared  buff/cache   available
Mem:            31Gi        28Gi       350Mi        18Mi       2.8Gi       2.5Gi
Swap:          8.0Gi       218Mi       7.8Gi

df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              3.2G  3.5M  3.2G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  196G   21G  167G  11% /
tmpfs                               16G     0   16G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          974M  235M  672M  26% /boot
tmpfs                              3.2G  104K  3.2G   1% /run/user/1000
overlay                            196G   21G  167G  11% /var/lib/docker/overlay2/8d96648f521ab12d49cb0169bfab4501b89aab0ed6053a8f5a4dec72f7d2d101/merged
tmpfs                               16G   20K   16G   1% /var/lib/docker/containers/8cdc1187f463870439857d7ca41ef8bba14663154326dacda1b578a62f6e45e9/mounts/secrets
overlay                            196G   21G  167G  11% /var/lib/docker/overlay2/b62af5bca1d36c10c873fb3a5ce60665dfef0d08943dde6837c4e801bb0edf95/merged
tmpfs                               16G   12K   16G   1% /var/lib/docker/containers/546eae30b2a7c9e2bc7a1104c53eafd9f7bb0707d56df380f0f57d0b6abff40b/mounts/secrets
overlay                            196G   21G  167G  11% /var/lib/docker/overlay2/b58f864c17ed892c290544d18dc810354425511f9a7e5138d0880b89cfd9406d/merged
tmpfs                               16G   12K   16G   1% /var/lib/docker/containers/b4b468438d4d85a1c838439369c9a3968b2130d6a2666a1541d940f6d99572f2/mounts/secrets

 uname -a
Linux lme-elk-srv 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

 lsb_release -a
LSB Version:    core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

- Relevant container logs: 
```
for name in $(sudo docker ps -a --format '{{.Names}}'); do echo -e "\n\n\n-----------$name----------"; sudo docker logs $name | tail -n 20; done
```
Increase the number of lines if your issue is not present, or include a relevant log of the erroring container
- Output of the relevant /var/log/cron_logs/ file

## Additional context
I added the Collection Server in the test bed and since it is local, then it shows up in the data! but nothing from the other servers.

**Comment by murphypa271327** [comment]
I did look and there isn't a /var/log/cron_logs  folder, that I could find.

**Comment by llwaterhouse** [comment]
Hello,

We suspect that "example.com:5985" is probably not correct unless your domain is [example.com](http://example.com/) 
[10:44](https://cisa-corp.slack.com/archives/C064V8Z9TE2/p1702482274064039)
So they need to find where they set something to “example.com” during their setup, and change that to the right domain






[10:44](https://cisa-corp.slack.com/archives/C064V8Z9TE2/p1702482245034899)
unless their domain is [example.com](http://example.com/) thats probably not the right cert
[10:44](https://cisa-corp.slack.com/archives/C064V8Z9TE2/p1702482274064039)
So they need to find where they set something to “example.com” during their setup, and change that to the right domain

**Comment by murphypa271327** [comment]
Good Morning,
The issue was resolved when I found this article -- Efficient Windows Event Collector Setup & Configuration (adamtheautomator.com)<https://adamtheautomator.com/windows-event-collector/>
1. Begin by opening up a command prompt and running wevtutil gl security. This will provide various information about the Security event log. But the piece to pay attention to is the channelAccess SDDL<https://docs.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-definition-language>.
You can see below an example of the SDDL you’ll need for the Security event log. The channelAccess line represents the permissions set on the event log. Copy the SDDL highlighted below and save it somewhere for later to add to a GPO.
***@***.***
2.  Create a GPO<https://www.dell.com/support/article/us/en/04/sln283093/windows-server-how-to-create-and-link-a-group-policy-object-using-the-group-policy-management-console> via the Group Policy Management Console. Inside of the GPO, navigate to Computer Configuration → Policies → Administrative Templates → Windows Components → Event Forwarding → Configure target subscription manager.
3.  Set the value for the target subscription manager to the WinRM endpoint on the collector. You will set the Server to be in the format:
Server=http://<FQDN of the collector>:5985/wsman/SubscriptionManager/WEC,Refresh=60
4.  Next, find the SDDL you copied earlier from running wevtutil gl security and paste it into the setting Computer Configuration → Policies → Administrative Templates → Windows Components → Event Log Service → Security → Configure log access.
Note that this SDDL will take precedence over all other permissions that have been configured for the event log.
You can see an example of what your GPO will look like below for the Security event log.
***@***.***

This set the permissions and the logs were available after that.



***@***.***Patrick Murphy
Network Systems Analyst
Office of Information Technology
301 S. Monroe Street
Tallahassee, FL  32301
ph: (850) 606-5560 / fax: (850) 606-5501
                              ***@***.******@***.***>

**Comment by llwaterhouse** [comment]
Glad you solved your issue!  Thank you for sharing your solution.
