### ISSUE TITLE
No logs in Elastic coming through 

### ISSUE THREAD

**Issue by cgalvez00** [cisagov/LME#94]
i am getting these errors 

"Failed to connect to backoff(async(tcp://EB.local:5044)): dial tcp 10.99.0.35:5044: connectex: No connection could be made because the target machine actively refused it.","service.name":"winlogbeat",
![image](https://github.com/cisagov/LME/assets/141188153/47bc1a41-f6bf-4d69-a6bf-e742c399b15b)

Can you help please, all the info i find on Elastic website say to make changes to certain files like 
filebeat.yml
logstash.conf

I used the script here provided by the team 

Please help me out.

**Comment by llwaterhouse** [comment]
In order to support you more fully, please resubmit this ticket with the "Bug or Error" template and fill out the requested information.
Thank you!
