### ISSUE TITLE
[BUG] EVENT ID 10129 After steps 1 and 2.

### ISSUE THREAD

**Issue by marceloalexei** [cisagov/LME#95]
Hello all. After completing chapter 1 and 2, I get an event ID 10129, stating the following :
"The WS-Management client is not listening for pushed events because there was a failure binding to the URL (...) in HTTP.SYS. 
It then asks me to use netsh http and make sure that URL is set to Network Service. 
Error code given is 5: %%5 apparently. 

The reason I'm not giving the URL is because it doesn't matter which URL I add to Network Service, whenever I add one, and retry the service or restart the WEC, I get the same event ID with a different URL asking me to do the same thing. I've added about 15 URLs before deciding it's just a bug that will continue to recreate itself. Any tips?

On the client side I can see Sysmon64 is running, and the on the wec I can see I have 1 computer active on my subscription. The error was there before I continued to chapter 2, but I decided to try chapter 2 in case that fixed the issue. 
I cannot see any logs in the forwarded events section of the event viewer. 
Very new to this - please let me know if you need any more information from me!

**Comment by llwaterhouse** [comment]
In order to support you more fully, please resubmit this ticket with the "Bug or Error" template and fill out the requested information.
Thank you!
